# Generated by Django 6.0.1 on 2026-01-17 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(db_index=True, max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['email'], name='clientes_email_fb2cd6_idx'), models.Index(fields=['numero_documento'], name='clientes_numero__b55e8a_idx'), models.Index(fields=['activo', '-fecha_creacion'], name='clientes_activo_dcf9ae_idx')],
            },
        ),
    ]
