# Generated by Django 6.0.1 on 2026-01-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0003_ordenmodel_lineaordenmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoriaModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_id', models.UUIDField(blank=True, null=True)),
                ('entidad_tipo', models.CharField(db_index=True, max_length=50)),
                ('entidad_id', models.UUIDField(db_index=True)),
                ('accion', models.CharField(db_index=True, max_length=20)),
                ('datos_previos', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria_registros',
                'ordering': ['-timestamp'],
                'permissions': [('view_auditoria', 'Can view audit logs')],
                'indexes': [models.Index(fields=['entidad_tipo', 'entidad_id'], name='auditoria_r_entidad_f00529_idx'), models.Index(fields=['accion', 'timestamp'], name='auditoria_r_accion_7ca909_idx'), models.Index(fields=['resultado', 'timestamp'], name='auditoria_r_resulta_c4a463_idx'), models.Index(fields=['usuario_id', 'timestamp'], name='auditoria_r_usuario_06e430_idx')],
            },
        ),
    ]
