# Generated by Django 6.0.1 on 2026-01-17 21:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_persistence', '0004_registroauditoriamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAccesoAPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('endpoint', models.CharField(db_index=True, max_length=200)),
                ('metodo', models.CharField(max_length=10)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('resultado_exitoso', models.BooleanField(db_index=True, default=False)),
                ('codigo_estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso API',
                'verbose_name_plural': 'Auditorías de Acceso API',
                'db_table': 'auditoria_acceso_api',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'usuario_id'], name='auditoria_a_timesta_c9924f_idx'), models.Index(fields=['-timestamp', 'endpoint'], name='auditoria_a_timesta_bbd68c_idx'), models.Index(fields=['-timestamp', 'resultado_exitoso'], name='auditoria_a_timesta_a4d799_idx')],
            },
        ),
    ]
